package com.fitness.app.service;

import org.springframework.stereotype.Service;

@Service
public class MailFormat {
    String billbody="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
			+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
			+ "<head>\n"
			+ "<!--[if gte mso 9]>\n"
			+ "<xml>\n"
			+ "  <o:OfficeDocumentSettings>\n"
			+ "    <o:AllowPNG/>\n"
			+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\n"
			+ "  </o:OfficeDocumentSettings>\n"
			+ "</xml>\n"
			+ "<![endif]-->\n"
			+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
			+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
			+ "  <meta name=\"x-apple-disable-message-reformatting\">\n"
			+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\n"
			+ "  <title></title>\n"
			+ "  \n"
			+ "    <style type=\"text/css\">\n"
			+ "      @media only screen and (min-width: 620px) {\n"
			+ "  .u-row {\n"
			+ "    width: 600px !important;\n"
			+ "  }\n"
			+ "  .u-row .u-col {\n"
			+ "    vertical-align: top;\n"
			+ "  }\n"
			+ "\n"
			+ "  .u-row .u-col-50 {\n"
			+ "    width: 300px !important;\n"
			+ "  }\n"
			+ "\n"
			+ "  .u-row .u-col-100 {\n"
			+ "    width: 600px !important;\n"
			+ "  }\n"
			+ "\n"
			+ "}\n"
			+ "\n"
			+ "@media (max-width: 620px) {\n"
			+ "  .u-row-container {\n"
			+ "    max-width: 100% !important;\n"
			+ "    padding-left: 0px !important;\n"
			+ "    padding-right: 0px !important;\n"
			+ "  }\n"
			+ "  .u-row .u-col {\n"
			+ "    min-width: 320px !important;\n"
			+ "    max-width: 100% !important;\n"
			+ "    display: block !important;\n"
			+ "  }\n"
			+ "  .u-row {\n"
			+ "    width: calc(100% - 40px) !important;\n"
			+ "  }\n"
			+ "  .u-col {\n"
			+ "    width: 100% !important;\n"
			+ "  }\n"
			+ "  .u-col > div {\n"
			+ "    margin: 0 auto;\n"
			+ "  }\n"
			+ "}\n"
			+ "body {\n"
			+ "  margin: 0;\n"
			+ "  padding: 0;\n"
			+ "}\n"
			+ "\n"
			+ "table,\n"
			+ "tr,\n"
			+ "td {\n"
			+ "  vertical-align: top;\n"
			+ "  border-collapse: collapse;\n"
			+ "}\n"
			+ "\n"
			+ "p {\n"
			+ "  margin: 0;\n"
			+ "}\n"
			+ "\n"
			+ ".ie-container table,\n"
			+ ".mso-container table {\n"
			+ "  table-layout: fixed;\n"
			+ "}\n"
			+ "\n"
			+ "* {\n"
			+ "  line-height: inherit;\n"
			+ "}\n"
			+ "\n"
			+ "a[x-apple-data-detectors='true'] {\n"
			+ "  color: inherit !important;\n"
			+ "  text-decoration: none !important;\n"
			+ "}\n"
			+ "\n"
			+ "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 47% !important; } #u_content_text_4 .v-text-align { text-align: center !important; } #u_content_text_3 .v-text-align { text-align: center !important; } #u_column_10 .v-col-border { border-top: 0px solid transparent !important;border-left: 0px solid transparent !important;border-right: 0px solid transparent !important;border-bottom: 0px solid transparent !important; } }\n"
			+ "    </style>\n"
			+ "  \n"
			+ "  \n"
			+ "\n"
			+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
			+ "\n"
			+ "</head>\n"
			+ "\n"
			+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffe200;color: #000000\">\n"
			+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\n"
			+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\n"
			+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffe200;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
			+ "  <tbody>\n"
			+ "  <tr style=\"vertical-align: top\">\n"
			+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
			+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffe200;\"><![endif]-->\n"
			+ "    \n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table id=\"u_content_image_1\" style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:20px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
			+ "  <tr>\n"
			+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
			+ "      \n"
			+ "      <img align=\"center\" border=\"0\" src=\"https://storage.googleapis.com/swag-swami-media/2020/02/fitness-freak-unisex-polo-t-shirt-design.jpg\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 31%;max-width: 179.8px;\" width=\"179.8\" class=\"v-src-width v-src-max-width\"/>\n"
			+ "      \n"
			+ "    </td>\n"
			+ "  </tr>\n"
			+ "</table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-image: url('https://cdn.templates.unlayer.com/assets/1611486242770-bg.png');background-repeat: no-repeat;background-position: center top;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-image: url('https://cdn.templates.unlayer.com/assets/1611486242770-bg.png');background-repeat: no-repeat;background-position: center top;background-color: transparent;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffe200; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-family: 'book antiqua', palatino; font-size: 72px; line-height: 100.8px;\"><strong><span style=\"line-height: 100.8px; font-size: 72px;\"><span style=\"line-height: 100.8px; font-size: 72px;\">GET FIT</span></span></strong></span></p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<div class=\"v-text-align\" align=\"center\">\n"
			+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Lato',sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:'Lato',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"http://localhost:3000\" style=\"height:37px; v-text-anchor:middle; width:118px;\" arcsize=\"0%\" stroke=\"f\" fillcolor=\"#ffe200\"><w:anchorlock/><center style=\"color:#272d31;font-family:'Lato',sans-serif;\"><![endif]-->\n"
			+ "    <a href=\"http://localhost:3000\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #272d31; background-color: #ffe200; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\n"
			+ "      <span style=\"display:block;padding:10px 20px;line-height:120%;\"><strong><span style=\"font-size: 14px; line-height: 16.8px;\">CLICK HERE</span></strong></span>\n"
			+ "    </a>\n"
			+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
			+ "</div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:50px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px 20px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffe200; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-family: 'book antiqua', palatino; font-size: 14px; line-height: 19.6px;\"><strong><span style=\"font-size: 48px; line-height: 67.2px;\">ARE YOU READY?</span></strong></span></p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"299\" class=\"v-col-border\" style=\"width: 299px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 1px solid #ffe200;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 1px solid #ffe200;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table id=\"u_content_text_4\" style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 160%; text-align: right; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 160%;\">When you're at the gym feeling like you'll never be one of those people who look like they've been at it their entire lives, remember that they all started somewhere.</p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"299\" class=\"v-col-border\" style=\"width: 299px;padding: 0px;border-top: 0px solid transparent;border-left: 1px solid #ffe200;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 1px solid #ffe200;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table id=\"u_content_text_3\" style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 160%; text-align: left; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 160%;\">&ldquo;Success isn&rsquo;t always about greatness. It&rsquo;s about consistency. Consistent hard work gains success. Greatness will come.&rdquo; &ndash; Dwayne Johnson</p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 40px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<div class=\"v-text-align\" align=\"center\">\n"
			+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Lato',sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:'Lato',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"http://localhost:3000\" style=\"height:42px; v-text-anchor:middle; width:142px;\" arcsize=\"2.5%\" strokecolor=\"#ffe200\" strokeweight=\"3px\" fillcolor=\"#131313\"><w:anchorlock/><center style=\"color:#ffe200;font-family:'Lato',sans-serif;\"><![endif]-->\n"
			+ "    <a href=\"http://localhost:3000\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffe200; background-color: #131313; border-radius: 1px;-webkit-border-radius: 1px; -moz-border-radius: 1px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #ffe200; border-top-style: solid; border-top-width: 3px; border-left-color: #ffe200; border-left-style: solid; border-left-width: 3px; border-right-color: #ffe200; border-right-style: solid; border-right-width: 3px; border-bottom-color: #ffe200; border-bottom-style: solid; border-bottom-width: 3px;\">\n"
			+ "      <span style=\"display:block;padding:8px 30px;line-height:120%;\"><span style=\"font-size: 22px; line-height: 26.4px;\">JOIN US</span></span>\n"
			+ "    </a>\n"
			+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
			+ "</div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"300\" class=\"v-col-border\" style=\"background-color: #ffe200;width: 300px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"background-color: #ffe200;width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 10px 0px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
			+ "  <tr>\n"
			+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
			+ "      \n"
			+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1611487161226-2.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 290px;\" width=\"290\" class=\"v-src-width v-src-max-width\"/>\n"
			+ "      \n"
			+ "    </td>\n"
			+ "  </tr>\n"
			+ "</table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"300\" class=\"v-col-border\" style=\"background-color: #131313;width: 300px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 2px solid #ffe200;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"background-color: #131313;width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 2px solid #ffe200;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:33px 10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffe200; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 140%;\"><strong><span style=\"font-size: 34px; line-height: 47.6px;\">NO PAIN</span></strong></p>\n"
			+ "<p style=\"font-size: 14px; line-height: 140%;\"><strong><span style=\"font-size: 34px; line-height: 47.6px;\">NO GAIN</span></strong></p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 49px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<div class=\"v-text-align\" align=\"center\">\n"
			+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Lato',sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:'Lato',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:36px; v-text-anchor:middle; width:122px;\" arcsize=\"3%\" strokecolor=\"#ffe200\" strokeweight=\"1px\" fillcolor=\"#131313\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Lato',sans-serif;\"><![endif]-->\n"
			+ "    <a href=\"\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #131313; border-radius: 1px;-webkit-border-radius: 1px; -moz-border-radius: 1px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #ffe200; border-top-style: solid; border-top-width: 1px; border-left-color: #ffe200; border-left-style: solid; border-left-width: 1px; border-right-color: #ffe200; border-right-style: solid; border-right-width: 1px; border-bottom-color: #ffe200; border-bottom-style: solid; border-bottom-width: 1px;\">\n"
			+ "      <span style=\"display:block;padding:10px 20px;line-height:120%;\"><span style=\"font-size: 14px; line-height: 16.8px;\">READ MORE</span></span>\n"
			+ "    </a>\n"
			+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
			+ "</div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"298\" class=\"v-col-border\" style=\"width: 298px;padding: 0px;border-top: 0px solid transparent;border-left: 2px solid #131313;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div id=\"u_column_10\" class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 2px solid #131313;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:50px 10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #131313; line-height: 120%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 120%;\"><strong><span style=\"font-size: 34px; line-height: 40.8px;\">DAILY</span></strong></p>\n"
			+ "<p style=\"font-size: 14px; line-height: 120%;\"><strong><span style=\"font-size: 34px; line-height: 40.8px;\">TRAINING</span></strong></p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 30px 34px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #131313; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 140%;\">&ldquo;The battles that count aren&rsquo;t the ones for gold medals. The struggles within yourself &ndash; the invisible, inevitable battles inside all of us &ndash; that&rsquo;s where it&rsquo;s at.&rdquo; &mdash; Jesse Owens</p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 61px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<div class=\"v-text-align\" align=\"center\">\n"
			+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Lato',sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:'Lato',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:36px; v-text-anchor:middle; width:122px;\" arcsize=\"11%\" strokecolor=\"#ffe200\" strokeweight=\"1px\" fillcolor=\"#131313\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Lato',sans-serif;\"><![endif]-->\n"
			+ "    <a href=\"\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #131313; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #ffe200; border-top-style: solid; border-top-width: 1px; border-left-color: #ffe200; border-left-style: solid; border-left-width: 1px; border-right-color: #ffe200; border-right-style: solid; border-right-width: 1px; border-bottom-color: #ffe200; border-bottom-style: solid; border-bottom-width: 1px;\">\n"
			+ "      <span style=\"display:block;padding:10px 20px;line-height:120%;\"><span style=\"font-size: 14px; line-height: 16.8px;\">READ MORE</span></span>\n"
			+ "    </a>\n"
			+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\n"
			+ "</div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"300\" class=\"v-col-border\" style=\"width: 300px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
			+ "  <tr>\n"
			+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\n"
			+ "      \n"
			+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1611488720648-XX.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 300px;\" width=\"300\" class=\"v-src-width v-src-max-width\"/>\n"
			+ "      \n"
			+ "    </td>\n"
			+ "  </tr>\n"
			+ "</table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "    <tbody>\n"
			+ "      <tr style=\"vertical-align: top\">\n"
			+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
			+ "          <span>&#160;</span>\n"
			+ "        </td>\n"
			+ "      </tr>\n"
			+ "    </tbody>\n"
			+ "  </table>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "\n"
			+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
			+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #131313;\">\n"
			+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\n"
			+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #131313;\"><![endif]-->\n"
			+ "      \n"
			+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" class=\"v-col-border\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\n"
			+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
			+ "  <div style=\"width: 100% !important;\">\n"
			+ "  <!--[if (!mso)&(!IE)]><!--><div class=\"v-col-border\" style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
			+ "  \n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "<div align=\"center\">\n"
			+ "  <div style=\"display: table; max-width:147px;\">\n"
			+ "  <!--[if (mso)|(IE)]><table width=\"147\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:147px;\"><tr><![endif]-->\n"
			+ "  \n"
			+ "    \n"
			+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 5px;\" valign=\"top\"><![endif]-->\n"
			+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 5px\">\n"
			+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
			+ "        <a href=\"https://facebook.com/\" title=\"Facebook\" target=\"_blank\">\n"
			+ "          <img src=\"https://cdn.tools.unlayer.com/social/icons/circle-black/facebook.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
			+ "        </a>\n"
			+ "      </td></tr>\n"
			+ "    </tbody></table>\n"
			+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "    \n"
			+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 5px;\" valign=\"top\"><![endif]-->\n"
			+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 5px\">\n"
			+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
			+ "        <a href=\"https://twitter.com/\" title=\"Twitter\" target=\"_blank\">\n"
			+ "          <img src=\"https://cdn.tools.unlayer.com/social/icons/circle-black/twitter.png\" alt=\"Twitter\" title=\"Twitter\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
			+ "        </a>\n"
			+ "      </td></tr>\n"
			+ "    </tbody></table>\n"
			+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "    \n"
			+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 5px;\" valign=\"top\"><![endif]-->\n"
			+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 5px\">\n"
			+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
			+ "        <a href=\"https://linkedin.com/\" title=\"LinkedIn\" target=\"_blank\">\n"
			+ "          <img src=\"https://cdn.tools.unlayer.com/social/icons/circle-black/linkedin.png\" alt=\"LinkedIn\" title=\"LinkedIn\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
			+ "        </a>\n"
			+ "      </td></tr>\n"
			+ "    </tbody></table>\n"
			+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "    \n"
			+ "    <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 0px;\" valign=\"top\"><![endif]-->\n"
			+ "    <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;margin-right: 0px\">\n"
			+ "      <tbody><tr style=\"vertical-align: top\"><td align=\"left\" valign=\"middle\" style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
			+ "        <a href=\"https://pinterest.com/\" title=\"Pinterest\" target=\"_blank\">\n"
			+ "          <img src=\"https://cdn.tools.unlayer.com/social/icons/circle-black/pinterest.png\" alt=\"Pinterest\" title=\"Pinterest\" width=\"32\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important\">\n"
			+ "        </a>\n"
			+ "      </td></tr>\n"
			+ "    </tbody></table>\n"
			+ "    <!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "    \n"
			+ "    \n"
			+ "    <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 30px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 160%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 160%;\">FitnessFreak is wellness booking &amp; subscription platform that enables users to browse and book fitness &amp; wellness services across a network of&nbsp; gyms in India making it a holistic destination for all things wellness. </p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
			+ "  <tbody>\n"
			+ "    <tr>\n"
			+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
			+ "        \n"
			+ "  <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
			+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 12px; line-height: 16.8px;\">&copy; FitnessFreak. All Rights Reserved.</span></p>\n"
			+ "  </div>\n"
			+ "\n"
			+ "      </td>\n"
			+ "    </tr>\n"
			+ "  </tbody>\n"
			+ "</table>\n"
			+ "\n"
			+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "<!--[if (mso)|(IE)]></td><![endif]-->\n"
			+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\n"
			+ "    </div>\n"
			+ "  </div>\n"
			+ "</div>\n"
			+ "\n"
			+ "\n"
			+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\n"
			+ "    </td>\n"
			+ "  </tr>\n"
			+ "  </tbody>\n"
			+ "  </table>\n"
			+ "  <!--[if mso]></div><![endif]-->\n"
			+ "  <!--[if IE]></div><![endif]-->\n"
			+ "</body>\n"
			+ "\n"
			+ "</html>";

    public String getBillbody() {
        return billbody;
    }

    public void setBillbody(String billbody) {
        this.billbody = billbody;
    }
}
